### ISSUE TITLE
Not able to run  sample code

### ISSUE THREAD

**Issue by panddu15** [google-research/tapas#23] opened 2020-06-20 17:51 UTC
Hi, I am stuck at result path in sample code it throwing following error
[Errno 2] No such file or directory: 'results/sqa/model/test_sequence.tsv'
I even checked in result folder i did not find the test_sequence.tsv file

**Comment by nopper** [comment] 2020-06-24 12:09
Hi @panddu15,

Can you provide more context and also paste the command you used, so we can try to reproduce the error from our side?

**Comment by panddu15** [comment] 2020-06-24 13:01
> Hi @panddu15,
> 
> Can you provide more context and also paste the command you used, so we can try to reproduce the error from our side?

     17     print()
---> 18     with open(results_path) as csvfile:
     19         reader = csv.DictReader(csvfile, delimiter='\t')
     20         for row in reader:

FileNotFoundError: [Errno 2] No such file or directory: 'results/sqa/model/test_sequence.tsv'

**Comment by nopper** [comment] 2020-06-24 13:04
Hi @panddu15,

Can you include the full command line you used that actually triggered the exception? And possibly explain what you are trying to do?

**Comment by muelletm** [comment] 2020-06-24 13:43
`test_sequence.tsv` should be output when you run the prediction for an SQA model.
Can you share how you ran the prediction job?

**Comment by panddu15** [comment] 2020-06-24 16:05
Hi, I was just trying to run the sample code and i did not do any changes in the code
Note:  i am running on it AWS machine where tapas is installed in root  and i am accessing jupyter from user.  

<img width="448" alt="tapas_error" src="https://user-images.githubusercontent.com/40796801/85591022-8b662980-b662-11ea-90e0-42b9e85210bb.PNG">

**Comment by mdmustafizurrahman** [comment] 2020-06-25 21:22
One question SQA task does not support COUNT,AVERAGE, MAX etc. For that we need WikiTable Task right. But as I mentioned multiple times, for none of your pretrained model you provided, WikiTable task is not working. Please kindly clarify or kindly provide a model trained on WikiTable.

**Comment by muelletm** [comment] 2020-06-26 13:39
@mdmustafizurrahman, yes we currently don't provide a model that support COUNT or AVERAGE (MAX is implicit so it should work). I'll see if we can realize the WTQ or WikiSQL model.

@panddu15, there must be another error before that. The actual prediction job seems to be failing or somehow it's configured to don't run the sequence prediction. Can you check if you are running with CPU or GPU?

**Comment by mdmustafizurrahman** [comment] 2020-06-26 16:45
@muelletm I would really appreciate if you could release WTQ

**Comment by panddu15** [comment] 2020-06-26 16:49
@muelletm I was running on CPU and there is no error prior to this.

**Comment by sbhttchryy** [comment] 2020-06-29 05:48
Hello @muelletm I too am facing the same error when trying to run the Colab notebook

**Comment by thomasmueller-google** [comment] 2020-08-06 08:40
The WTQ model was released today. Closing feel free to reopen if there is still an issue with the colab.

**Comment by sophgit** [comment] 2020-12-09 12:52
I somehow managed to ruin my installed packages . Now I'm trying to do the tapas installation (Ubuntu 20.04) all over again and received the exact same error as described above (except for WTQ instead of SQA).: FileNotFoundError: [Errno 2] No such file or directory: 'results/sqa/model/test_sequence.tsv' 
No GPU. It did not create the test_sequence.tsv file. Any idea how to solve this?

**Comment by thomasmueller-google** [comment] 2020-12-09 16:44
That's odd, there should be no `test_sequence.tsv` for WTQ just `test.tsv`.

Can you share how you ran this?
And maybe also a stack trace?

**Comment by sophgit** [comment] 2020-12-09 17:11
oh, so sorry, yes, the Error was: FileNotFoundError: [Errno 2] No such file or directory: 'results/wtq/model/test.tsv'

installed tapas with pip install ./tapas/  and there were no errors until the prediction, where it didn't find the test.tsv, because it simply didn't create it.
I managed to "solve" the problem by shutting all notebooks and Ubuntu down and then running the same line _pip install ./tapas/_ again... not sure what caused or solved the problem, but now it works.
Thank you anyhow!!

**Closed** 2020-12-09 17:13 UTC
