### ISSUE TITLE
Basic steps to try this on my data?

### ISSUE THREAD

**Issue by scottbouma** [google-research/tapas#10] opened 2020-05-22 22:00 UTC
Hi,  I would love to try this out on some of our data.   The basic experiment I'm thinking of is based on user interactions with specific features in our product.  So in general the table would have columns such as:   date, user_id, user_meta1, user_meta2, ..., feature_X_interaction_count, feature_Y_interaction_count, ...

I'd like to ask questions like "How many new users interacted with feature X?" or "what country has the highest percentage of users who interacted with feature Y?", or "which features do users from North America use the most?"; etc.

Does this sound like a feasible experiment, and if so can you give me some very high-level steps to try.  E.g. can I start with one of your pretrained models and either fine-tune or predict directly?  If I do need to train from scratch, can you suggest how I would generate training examples?

Thanks so much in advance for pointing me in the right direction!

**Comment by muelletm** [comment] 2020-05-25 07:28
Duplicate of #7.

We discuss some ways to use custom data in that issue. Feel free to respond there if something remains unclear.

**Closed by muelletm** 2020-05-25 07:28 UTC
Labels: duplicate
